# Generated by Django 3.0.1 on 2019-12-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mb',
            field=models.BooleanField(default=False, help_text='Designates whether the user can edit bookings on privileged events and alter materials.', verbose_name='materiaalboer status'),
        ),
    ]
