# Generated by Django 3.0.4 on 2020-03-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_group_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(help_text="URL short name", unique=True),
        ),
    ]
