# Generated by Django 3.0.1 on 2019-12-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191229_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='part_of_day',
            field=models.CharField(choices=[('GR', 'Group'), ('CO', 'Commission')], default='CO', help_text='What type is the group?', max_length=2),
        ),
    ]
