# Generated by Django 3.0.1 on 2019-12-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_group_part_of_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='part_of_day',
            new_name='type',
        ),
    ]
