# Generated by Django 3.1.1 on 2020-09-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20200809_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="What group should this user be associated with?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.group",
                verbose_name="group",
            ),
        ),
    ]
