# Generated by Django 3.0.1 on 2019-12-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191230_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_mb',
        ),
    ]
