# Generated by Django 3.0.1 on 2019-12-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_role'),
        ('users', '0006_remove_user_is_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('GR', 'Group'), ('CO', 'Commission')], default='CO', help_text='What type is the group?', max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, help_text='What group should this user be associated with?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The roles this user has. A user will get all permissions granted to each of their roles.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='roles'),
        ),
    ]
