# Generated by Django 4.2a1 on 2023-01-22 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_auto_20210414_2135"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": [("view_admin", "Can open the site admin page")]},
        ),
    ]
