apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: database
  name: database
  namespace: dbase
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/dbase-backend-network: "true"
        io.kompose.service: database
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: dbase-configmap
          image: postgres:15.2
          livenessProbe:
            exec:
              command:
                - pg_isready
            periodSeconds: 90
          name: database
          resources:
            limits:
              memory: 50M
            requests:
              memory: 30M
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      restartPolicy: Always
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data
