apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: memcached
  name: memcached
  namespace: dbase
spec:
  ports:
    - name: "11211"
      port: 11211
      targetPort: 11211
  selector:
    io.kompose.service: memcached
