apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nginx-tcp
  name: nginx-tcp
  namespace: dbase
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
