apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: dbase
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/dbase-backend-network: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - image: gafderkspersonal/dbase-nginx:latest
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:80/
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 90
            timeoutSeconds: 30
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "52428800"
            requests:
              memory: "31457280"
          volumeMounts:
            - mountPath: /opt/services/dbase/media
              name: media-volume
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-volume
            readOnly: true
status: {}
