apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
  namespace: dbase
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/dbase-backend-network: "true"
        io.kompose.service: web
    spec:
      containers:
        - args:
            - gunicorn
            - --bind
            - 0.0.0.0:8000
            - --timeout
            - "120"
            - --workers
            - "2"
            - dbase.wsgi
          envFrom:
            - configMapRef:
                name: dbase-configmap
          image: gafderkspersonal/dbase-web:latest
          livenessProbe:
            httpGet:
              port: 8000
              httpHeaders:
                - name: Host
                  value: localhost
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 90
            timeoutSeconds: 30
          name: web
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              memory: "324288e3"
            requests:
              memory: "262144e3"
          volumeMounts:
            - mountPath: /app/media
              name: media-volume
      restartPolicy: Always
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-volume
status: {}
