version: "2"
plugins:
  stylelint:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      config: .eslintrc.json
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
  - "**/migrations/*"
  - "**/tests/*"
