language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
node_js: "12"
env:
  global:
    - DATABASE_URL="sqlite:///db.sqlite3" DEBUG=off
services:
  - xvfb
addons:
  firefox: latest
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install pipenv
  - pipenv install --dev
  - npm install -g gulp-cli
  - npm install
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - python manage.py compilemessages
script:
  - python manage.py test
