language: python
python:
  - "3.6"
  - "3.7"
env:
  global:
    - DATABASE_URL="sqlite:///db.sqlite3" DEBUG=off
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - python manage.py migrate
script:
  - python manage.py test
