version: "3.1"

volumes:
  postgresql_data:
  static_volume:
  media_volume:


services:
  nginx:
    image: nginx:1.25.3
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/opt/services/dbase/static:ro
      - media_volume:/opt/services/dbase/media:ro
    depends_on:
      - web
    networks:
      - backend_network
  database:
    image: postgres:15.2
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - docker.env
    networks:
      - backend_network
  web:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 --timeout 120 --workers 2 dbase.wsgi
    depends_on:
      - database
      - memcached
    env_file:
      - docker.env
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - backend_network
  memcached:
    image: memcached:1.6
    expose:
      - 11211
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
