# Generated by Django 2.2.6 on 2019-11-24 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField()),
                ('archived', models.BooleanField()),
                ('booking_start', models.DateTimeField()),
                ('booking_end', models.DateTimeField()),
                ('event_start', models.DateField()),
                ('event_end', models.DateField()),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'get_latest_by': 'event_start',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField()),
                ('day', models.DateField()),
                ('part_of_day', models.CharField(choices=[('MO', 'Morning'), ('AF', 'Afternoon'), ('EV', 'Evening'), ('NI', 'Night'), ('DA', 'Day')], default='MO', max_length=2)),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
                ('gm', models.BooleanField(verbose_name='GM')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Category')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Material')),
            ],
            options={
                'verbose_name': 'material alias',
                'verbose_name_plural': 'material aliases',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=150)),
                ('part_of_day', models.CharField(max_length=150)),
                ('workweek', models.CharField(blank=True, max_length=150, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.CharField(max_length=150)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Event')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Game')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Group')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Material')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
            },
        ),
    ]
