# Generated by Django 3.0.1 on 2019-12-31 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.Event",
                verbose_name="event",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="booking.Game",
                verbose_name="game",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.Group",
                verbose_name="group",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="booking.Material",
                verbose_name="material",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="requester",
            ),
        ),
    ]
