# Generated by Django 2.2.6 on 2019-11-26 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191124_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='RateClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='rate')),
            ],
            options={
                'verbose_name': 'rate class',
                'verbose_name_plural': 'rate classes',
            },
        ),
        migrations.RemoveField(
            model_name='material',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='privileged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='lendable',
            field=models.BooleanField(default=True, help_text='Should this material be shown for lending?', verbose_name='lendable'),
        ),
        migrations.AddField(
            model_name='material',
            name='stock',
            field=models.CharField(blank=True, help_text='How many exemplars are there of this material?', max_length=150, verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ManyToManyField(to='booking.Category'),
        ),
        migrations.AlterField(
            model_name='material',
            name='gm',
            field=models.BooleanField(help_text='Is GM needed for this material?', verbose_name='GM'),
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='booking.Material')),
            ],
            options={
                'verbose_name': 'material image',
                'verbose_name_plural': 'material images',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Where can this material be found?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Location'),
        ),
        migrations.AddField(
            model_name='material',
            name='rate_class',
            field=models.ForeignKey(blank=True, help_text='What rate class should this material be associated with?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.RateClass'),
        ),
    ]
