# Generated by Django 3.0.1 on 2019-12-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_auto_20191231_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="name"),
        ),
    ]
