# Generated by Django 2.2.6 on 2019-11-24 20:38

from django.db import migrations, transaction
import csv
import os


def load_initial_data(apps, schema_editor):
    with transaction.atomic():
        # get the correct versions of models using the app registry
        Material = apps.get_model("booking", "Material")
        #Inspection = apps.get_model("api", "Inspection")

        # This is where your migration logic will go.
        # For my use case i needed to get unique businesses and
        # transform data from the csv file into the schema i wanted
        with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../migrations/materiaal.csv')) as csv_file:
            reader = csv.reader(csv_file, delimiter=',', quotechar='"')
            header = next(reader)

            materials = []
            #inspections = []

            for row in reader:
                name, description, category, gm, the_id = row
                material = Material(
                    name=name,
                    description=description,
                    # TODO add category
                    gm=(gm == "Ja"),
                )
                materials.append(material)

            Material.objects.bulk_create(materials)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191229_1922'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
