# Generated by Django 3.0.1 on 2020-01-04 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0004_auto_20200101_1531"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="part_of_day",
            new_name="part_of_day_code",
        ),
        migrations.AddField(
            model_name="game",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Where do you need the materials for this game to be delivered? This defaults to the location of the part of day.",
                max_length=250,
                null=True,
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="E.g. for food: when and where do you need it?",
                max_length=250,
                null=True,
                verbose_name="comment",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.Event",
                verbose_name="event",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bookings",
                to="booking.Game",
                verbose_name="game",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bookings",
                to="users.Group",
                verbose_name="group",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bookings",
                to="booking.Material",
                verbose_name="material",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="requester",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="games",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="categories",
            field=models.ManyToManyField(
                related_name="materials", to="booking.Category"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="rate_class",
            field=models.ForeignKey(
                blank=True,
                help_text="What rate class should this material be associated with?",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="materials",
                to="booking.RateClass",
                verbose_name="rate class",
            ),
        ),
        migrations.AlterField(
            model_name="materialalias",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aliases",
                to="booking.Material",
                verbose_name="material",
            ),
        ),
        migrations.CreateModel(
            name="PartOfDay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        help_text="On what day are the materials needed?",
                        verbose_name="day",
                    ),
                ),
                (
                    "part_of_day_code",
                    models.CharField(
                        choices=[
                            ("MO", "Morning"),
                            ("AF", "Afternoon"),
                            ("EV", "Evening"),
                            ("NI", "Night"),
                            ("DA", "Day"),
                        ],
                        default="MO",
                        help_text="At what part of the day are the materials needed?",
                        max_length=2,
                        verbose_name="part of day",
                    ),
                ),
                ("start_time", models.TimeField(null=True, verbose_name="start time")),
                ("end_time", models.TimeField(null=True, verbose_name="end time")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Where do you need the materials for this part of day to be delivered?",
                        max_length=250,
                        null=True,
                        verbose_name="location",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.Event",
                        verbose_name="event",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.Group",
                        verbose_name="group",
                    ),
                ),
            ],
        ),
    ]
