# Generated by Django 3.0.1 on 2019-12-30 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191230_1514'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0005_auto_20191230_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.CharField(max_length=150, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(help_text='On what day are the materials needed?', verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Game', verbose_name='game'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='part_of_day',
            field=models.CharField(choices=[('MO', 'Morning'), ('AF', 'Afternoon'), ('EV', 'Evening'), ('NI', 'Night'), ('DA', 'Day')], default='MO', help_text='At what part of the day are the materials needed?', max_length=2, verbose_name='part of day'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='requester'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='workweek',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='workweek'),
        ),
        migrations.AlterField(
            model_name='event',
            name='booking_end',
            field=models.DateTimeField(help_text='When should the event become privileged?', verbose_name='end date booking period'),
        ),
        migrations.AlterField(
            model_name='event',
            name='booking_start',
            field=models.DateTimeField(help_text='When should the event be opened for booking?', verbose_name='start date booking period'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end',
            field=models.DateField(help_text='What is the last day of the event?', verbose_name='event end date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateField(help_text='What is the first day of the event?', verbose_name='event start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='locked',
            field=models.BooleanField(default=False, help_text='Manually lock the booking such that users cannot change bookings (except admin).', verbose_name='locked'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='privileged_booking_end',
            field=models.DateTimeField(help_text='When should the event become locked?', verbose_name='end date privileged booking period'),
        ),
        migrations.AlterField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=True, help_text='Should the event be visible?', verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='game',
            name='day',
            field=models.DateField(help_text='On what day are the materials needed?', verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='order',
            field=models.PositiveIntegerField(editable=False, help_text='Defines an ordering for the games within a day/part of day', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='game',
            name='part_of_day',
            field=models.CharField(choices=[('MO', 'Morning'), ('AF', 'Afternoon'), ('EV', 'Evening'), ('NI', 'Night'), ('DA', 'Day')], default='MO', help_text='At what part of the day are the materials needed?', max_length=2, verbose_name='part of day'),
        ),
        migrations.AlterField(
            model_name='material',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Where can this material be found?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='material',
            name='rate_class',
            field=models.ForeignKey(blank=True, help_text='What rate class should this material be associated with?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.RateClass', verbose_name='rate class'),
        ),
        migrations.AlterField(
            model_name='materialalias',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='materialimage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='booking.Material', verbose_name='material'),
        ),
    ]
