# Generated by Django 3.0.1 on 2020-01-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("booking", "0005_auto_20200104_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.Event",
                verbose_name="event",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.Group",
                verbose_name="group",
            ),
            preserve_default=False,
        ),
    ]
