# Generated by Django 3.0.1 on 2020-01-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_auto_20200112_1835"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="part_of_day_code",),
        migrations.AlterField(
            model_name="booking",
            name="game",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.Game",
                verbose_name="game",
            ),
            preserve_default=False,
        ),
    ]
