# Generated by Django 3.0.1 on 2020-01-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_auto_20200113_2348"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ("day", "part_of_day", "order"),
                "verbose_name": "game",
                "verbose_name_plural": "games",
            },
        ),
    ]
