# Generated by Django 3.0.1 on 2020-01-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0010_auto_20200114_2218"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["day", "part_of_day", "order"],
                "verbose_name": "game",
                "verbose_name_plural": "games",
            },
        ),
        migrations.AlterField(
            model_name="game",
            name="order",
            field=models.PositiveIntegerField(
                default=1,
                editable=False,
                help_text="Defines an ordering for the games within a day/part of day",
                verbose_name="order",
            ),
        ),
    ]
