# Generated by Django 3.0.1 on 2020-01-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0011_auto_20200116_2210"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="day",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="event",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="group",
        ),
        migrations.AlterField(
            model_name="booking",
            name="workweek",
            field=models.BooleanField(default=1, verbose_name="workweek"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Defines an ordering for the games within a day/part of day",
                verbose_name="order",
            ),
        ),
    ]
