# Generated by Django 3.0.1 on 2020-01-24 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0012_auto_20200119_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bookings",
                to="booking.Material",
                verbose_name="material",
            ),
        ),
    ]
