# Generated by Django 3.0.4 on 2020-03-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0014_auto_20200306_2337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="lendable",
            field=models.BooleanField(
                default=False,
                help_text="Should this material be shown for lending?",
                verbose_name="lendable",
            ),
        ),
        migrations.CreateModel(
            name="ListViewFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="description"
                    ),
                ),
                ("enabled", models.BooleanField(verbose_name="Enabled")),
                (
                    "the_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, editable=False
                    ),
                ),
                ("gm", models.BooleanField(null=True, verbose_name="GM")),
                (
                    "excluded_categories",
                    models.ManyToManyField(
                        related_name="_listviewfilter_excluded_categories_+",
                        to="booking.Category",
                        verbose_name="excluded categories",
                    ),
                ),
                (
                    "included_categories",
                    models.ManyToManyField(
                        related_name="_listviewfilter_included_categories_+",
                        to="booking.Category",
                        verbose_name="included categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "list view filter",
                "verbose_name_plural": "list view filters",
                "ordering": ["the_order"],
            },
        ),
    ]
