# Generated by Django 3.0.4 on 2020-03-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_auto_20200312_1742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listviewfilter",
            name="excluded_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="_listviewfilter_excluded_categories_+",
                to="booking.Category",
                verbose_name="excluded categories",
            ),
        ),
        migrations.AlterField(
            model_name="listviewfilter",
            name="included_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="_listviewfilter_included_categories_+",
                to="booking.Category",
                verbose_name="included categories",
            ),
        ),
    ]
