# Generated by Django 3.0.4 on 2020-03-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0017_auto_20200312_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(help_text="URL short name", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="listviewfilter",
            name="the_order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="Filter order"
            ),
        ),
    ]
