# Generated by Django 3.0.4 on 2020-03-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0018_auto_20200315_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(help_text="URL short name", unique=True),
        ),
    ]
