# Generated by Django 3.0.4 on 2020-03-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0019_auto_20200317_2102"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "default_permissions": [],
                "permissions": [
                    (
                        "can_change_other_groups_bookings",
                        "Can change bookings of other groups",
                    ),
                    (
                        "can_view_others_groups_bookings",
                        "Can view bookings of other groups",
                    ),
                ],
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
            },
        ),
        migrations.AlterModelOptions(
            name="game",
            options={
                "default_permissions": [],
                "ordering": ["day", "part_of_day", "order"],
                "verbose_name": "game",
                "verbose_name_plural": "games",
            },
        ),
        migrations.AlterModelOptions(
            name="partofday",
            options={
                "default_permissions": [],
                "verbose_name": "daypart",
                "verbose_name_plural": "dayparts",
            },
        ),
        migrations.AlterField(
            model_name="game",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Defines an ordering for the games within a day(part)",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="part_of_day",
            field=models.CharField(
                choices=[
                    ("DA", "Day"),
                    ("MO", "Morning"),
                    ("AF", "Afternoon"),
                    ("EV", "Evening"),
                    ("NI", "Night"),
                ],
                default="MO",
                help_text="At what daypart are the materials needed?",
                max_length=2,
                verbose_name="daypart",
            ),
        ),
        migrations.AlterField(
            model_name="partofday",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Where do you need the materials for this daypart to be delivered?",
                max_length=250,
                null=True,
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="partofday",
            name="part_of_day_code",
            field=models.CharField(
                choices=[
                    ("DA", "Day"),
                    ("MO", "Morning"),
                    ("AF", "Afternoon"),
                    ("EV", "Evening"),
                    ("NI", "Night"),
                ],
                default="MO",
                help_text="At what daypart are the materials needed?",
                max_length=2,
                verbose_name="daypart",
            ),
        ),
    ]
