# Generated by Django 3.0.5 on 2020-04-11 19:35

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_auto_20200325_2144"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material", old_name="stock", new_name="stock_unit",
        ),
        migrations.AlterField(
            model_name="materialimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                upload_to="materials", verbose_name="image"
            ),
        ),
    ]
