# Generated by Django 3.0.5 on 2020-04-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0021_auto_20200411_2135"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="stock_value",
            field=models.FloatField(
                help_text="How many exemplars are there of this material?",
                null=True,
                verbose_name="stock value",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="stock_unit",
            field=models.CharField(
                blank=True,
                help_text="Specify a unit for the stock. E.g. meters.",
                max_length=150,
                verbose_name="stock unit",
            ),
        ),
    ]
