# Generated by Django 3.0.5 on 2020-04-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0023_auto_20200411_2232"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialimage",
            options={
                "ordering": ["image_order"],
                "verbose_name": "material image",
                "verbose_name_plural": "material images",
            },
        ),
        migrations.AddField(
            model_name="materialimage",
            name="image_order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
