# Generated by Django 3.0.5 on 2020-04-20 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0024_auto_20200420_1011"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        upload_to="material-attachments", verbose_name="attachment"
                    ),
                ),
                (
                    "attachment_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, editable=False
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="attachments",
                        to="booking.Material",
                        verbose_name="material",
                    ),
                ),
            ],
            options={
                "verbose_name": "material attachment",
                "verbose_name_plural": "material attachments",
                "ordering": ["attachment_order"],
            },
        ),
    ]
