# Generated by Django 3.0.5 on 2020-04-21 20:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0025_materialattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Additional information about the material. Displayed in the shop.",
                verbose_name="description",
            ),
        ),
    ]
