# Generated by Django 3.0.5 on 2020-04-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0026_auto_20200421_2250"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={
                "get_latest_by": "last_modified",
                "verbose_name": "material",
                "verbose_name_plural": "materials",
            },
        ),
        migrations.AddField(
            model_name="material",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
