# Generated by Django 3.0.6 on 2020-05-22 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0027_auto_20200424_2154"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "default_permissions": [],
                "permissions": [
                    (
                        "change_other_groups_bookings",
                        "Can change bookings of other groups",
                    ),
                    (
                        "view_others_groups_bookings",
                        "Can view bookings of other groups",
                    ),
                ],
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "get_latest_by": "event_end",
                "ordering": ["-event_end"],
                "permissions": [
                    ("view_hidden_events", "Can view hidden events"),
                    ("change_privileged_events", "Can change privileged events"),
                    ("change_locked_events", "Can change locked events"),
                ],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
    ]
