# Generated by Django 3.0.6 on 2020-06-05 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0028_auto_20200522_1951"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "get_latest_by": "event_end",
                "ordering": ["-event_end"],
                "permissions": [
                    ("view_hidden_events", "Can view hidden events"),
                    ("book_on_privileged_events", "Can book on privileged events"),
                    ("book_on_locked_events", "Can book on locked events"),
                ],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
    ]
