# Generated by Django 3.0.8 on 2020-08-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0029_auto_20200605_2130"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialattachment",
            name="description",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="description"
            ),
        ),
    ]
