# Generated by Django 3.1.1 on 2020-09-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0030_materialattachment_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "get_latest_by": "event_end",
                "ordering": ["-visible", "-event_end"],
                "permissions": [
                    ("view_hidden_events", "Can view hidden events"),
                    ("book_on_privileged_events", "Can book on privileged events"),
                    ("book_on_locked_events", "Can book on locked events"),
                ],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="booking.material",
                verbose_name="material",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Where can this material be found?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="booking.location",
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="rate_class",
            field=models.ForeignKey(
                blank=True,
                help_text="What rate class should this material be associated with?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="booking.rateclass",
                verbose_name="rate class",
            ),
        ),
        migrations.AlterField(
            model_name="materialalias",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="booking.material",
                verbose_name="material",
            ),
        ),
        migrations.AlterField(
            model_name="materialattachment",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="booking.material",
                verbose_name="material",
            ),
        ),
        migrations.AlterField(
            model_name="materialimage",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="booking.material",
                verbose_name="material",
            ),
        ),
    ]
