# Generated by Django 4.2a1 on 2023-01-25 21:46

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0036_alter_rateclass_rate_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="lendable_stock_value",
            field=models.FloatField(
                blank=True,
                help_text="How many exemplars of this materials are lendable?",
                null=True,
                verbose_name="lendable stock value",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="categories",
            field=mptt.fields.TreeManyToManyField(
                related_name="materials",
                to="booking.category",
                verbose_name="categories",
            ),
        ),
    ]
