name: ci

on:
  push:
    branches:
      - "master"

env:
  WEB_TEST_TAG: gafderkspersonal/dbase-web:test
  WEB_LATEST_TAG: gafderkspersonal/dbase-web:latest
  NGINX_TEST_TAG: gafderkspersonal/dbase-nginx:test
  NGINX_LATEST_TAG: gafderkspersonal/dbase-nginx:latest

jobs:
  docker:
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Web Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          target: runtime
          context: .
          load: true
          tags: ${{ env.WEB_TEST_TAG }}
      - name: Test web container
        run: |
          docker run --rm ${{ env.WEB_TEST_TAG }}
      - name: Nginx Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          target: runtime
          context: .
          load: true
          tags: ${{ env.NGINX_TEST_TAG }}
      - name: Test nginx container
        run: |
          docker run --rm ${{ env.NGINX_TEST_TAG }}
      - name: Build and push web container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: runtime
          tags: ${{ env.WEB_LATEST_TAG }}
      - name: Build and push nginx container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: nginx
          tags: ${{ env.NGINX_LATEST_TAG }}
