# This workflow will run PyUp security scans on all dependencies that are installed into the environment.

name: PyUp Security Scan

on:
  push: # Run on every push to any branch
  pull_request: # Run on new pull requests

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: pyupio/safety@2.3.2
        with:
          api-key: ${{secrets.SAFETY_API_KEY}}
          scan: 'file'
